---
- name: Download etcd binaries
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /tmp/etcd.tar.gz
    checksum: "sha256:..."

- name: Extract etcd binaries
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: "--strip-components=1 --wildcards '*/etcd*'"

- name: Create etcd data directory
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Create etcd systemd service
  template:
    src: ../../etcd/templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart etcd

- name: Enable and start etcd service
  systemd:
    name: etcd
    enabled: yes
    state: started
