---
- name: Install HAProxy and Keepalived
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy
    - keepalived

- name: Configure HAProxy
  template:
    src: ../../load-balancer/templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived

- name: Enable and start HAProxy
  systemd:
    name: haproxy
    enabled: yes
    state: started

- name: Enable and start Keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started
