apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tenant-b
  name: tenant-b-admin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "delete"]
