---
- name: Disable root login if configured
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin {{ 'yes' if ssh_restrict_root == false else 'no' }}"
    backup: yes
  notify: Restart SSH

- name: Disable password authentication (if enabled)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication {{ 'yes' if ssh_password_auth == true else 'no' }}"
    backup: yes
  notify: Restart SSH

- name: Ensure SSH only allows key-based authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    backup: yes
  notify: Restart SSH
