---
firewall_ports:
  - 6443/tcp  # Kubernetes API Server
  - 2379-2380/tcp  # etcd server client API
  - 10250/tcp  # kubelet API
  - 10257/tcp  # kube-controller-manager
  - 10259/tcp  # kube-scheduler
