---
- name: Disable root login if configured
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin {{ 'yes' if ssh_restrict_root == false else 'no' }}"
    backup: yes
  notify: Restart SSH

- name: Disable password authentication (if enabled)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication {{ 'yes' if ssh_password_auth == true else 'no' }}"
    backup: yes
  notify: Restart SSH

- name: Ensure SSH only allows key-based authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    backup: yes
  notify: Restart SSH

- name: Ensure SSH package is latest
  ansible.builtin.yum:
    name: openssh-server
    state: latest
  tags: ssh,patch

- name: Configure SSH daemon
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart SSH
  tags: ssh,config

- name: Remove weak MAC algorithms
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
    insertafter: '^#MACs'
  notify: Restart SSH
  tags: ssh,crypto



- name: Apply filesystem protections
  ansible.builtin.mount:
    path: /tmp
    state: present
    opts: defaults,noexec,nosuid,nodev
    fstype: tmpfs
  tags: filesystem

- name: Disable core dumps
  ansible.builtin.sysctl:
    name: kernel.core_pattern
    value: /dev/null
    sysctl_set: yes
  tags: kernel
