apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-server-error-alert
  namespace: monitoring
spec:
  groups:
    - name: api_server_alerts
      rules:
        - alert: HighAPIErrorRate
          expr: rate(apiserver_request_total{job="kube-apiserver",code=~"5.."}[1m]) > 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High API Server error rate"
            description: "API Server error rate is above 1 request per minute"
