apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: etcd-latency-alert
  namespace: monitoring
spec:
  groups:
    - name: etcd_alerts
      rules:
        - alert: HighETCDLatency
          expr: etcd_server_latency_seconds_sum{job="kube-apiserver"} / etcd_server_latency_seconds_count{job="kube-apiserver"} > 0.5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "ETCD latency is high"
            description: "ETCD latency is above 500ms"
