---
- import_tasks: firewall.yml
  when: firewall_enabled | default(false)

- import_tasks: ssh.yml
  when: ssh_hardening | default(false)

- import_tasks: kernel.yml
  when: kernel_tuning | default(false)

- import_tasks: hardening.yml
  when: system_hardening | default(false)
