---
- name: Ensure auditd is installed
  ansible.builtin.yum:
    name: audit
    state: present

- name: Enable auditd
  ansible.builtin.systemd:
    name: auditd
    enabled: yes
    state: started
