apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2022-12-17T04-58-35Z
        args:
          - server
          - /data
        ports:
          - containerPort: 9000
        env:
          - name: MINIO_ACCESS_KEY
            value: "*"
          - name: MINIO_SECRET_KEY
            value: "*"
        volumeMounts:
          - name: minio-data
            mountPath: /data
      volumes:
      - name: minio-data
        emptyDir: {}
