apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: s3
  objectStorage:
    bucket: velero-backups  # The name of the MinIO bucket for backups
    prefix: backups
  config:
    region: us-east-1
    s3Url: http://minio.minio.svc.cluster.local:9000
  default: true
