apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  schedule: "0 0 * * *"  # Cron schedule for every day at midnight
  backupTemplate:
    includedNamespaces:
      - default
      - kube-system
    excludedResources:
      - events
    snapshotVolumes: true
    volumeSnapshotLocations:
      - default
