---
- name: Reset Kubernetes cluster
  hosts: k8s-cluster
  become: true
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f
      ignore_errors: yes

    - name: Remove CNI config
      file:
        path: /etc/cni/net.d
        state: absent

    - name: Clean up iptables
      command: "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
      ignore_errors: yes

    - name: Remove kubectl config
      file:
        path: "~/.kube"
        state: absent
