---
- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    shell: /bin/false
    comment: "Node Exporter User"

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
#    checksum: "sha256:CHECKSUM_GOES_HERE"

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Install Node Exporter binary
  copy:
    remote_src: yes
    src: "/tmp/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: Create Node Exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify: restart node_exporter

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
