---
- name: Install firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Open required firewall ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ firewall_ports }}"

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
  notify: Reload firewall


- name: Apply base firewall rules
  ansible.builtin.firewalld:
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
    service: "{{ item }}"
  loop: "{{ firewall_allowed_services }}"
  notify: Reload firewalld
  tags: firewall,rules
