site_name: Kubernetes Project Documentation
theme:
  name: 'material'

nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Security: security.md
  - Terraform: terraform.md
  - Architecture: architecture.md

