---
- name: Download Calico manifest
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /root/calico.yaml

- name: Apply Calico network
  command: kubectl apply -f /root/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
