---
- name: Install and configure auditd
  ansible.builtin.yum:
    name: audit
    state: present

- name: Enable auditd
  ansible.builtin.systemd:
    name: auditd
    enabled: yes
    state: started

- name: Install and configure fail2ban
  ansible.builtin.yum:
    name: fail2ban
    state: present

- name: Enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: Ensure package updates are installed
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: yes
