---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install containerd
  apt:
    name: "containerd.io={{ containerd_version }}*"
    state: present
    force: yes

- name: Configure containerd
  template:
    src: daemon.json.j2
    dest: "{{ containerd_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart containerd

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
